Implimented George to drive the GP
StuartLittlefair/lfit_python pull request #6
Opened 2019-04-30 12:51 UTC by wildjames

2019-04-30 15:02 UTC, StuartLittlefair reviewed
Looks good James. I think it could benefit from a couple of tweaks which would fix the change points routine, and use fewer kernels in general. 

these tweaks would make the code more efficient, though as far as I can tell, what you have here works correctly...

2019-04-30 15:02 UTC, StuartLittlefair commented on mcmcfit.py
>          changepoints = self.calcChangepoints(phi)
I think ```calcChangepoints``` itself needs looking at, to check the logic works. You could use that opportunity to change exactly what ```calcChangepoints``` returns if that makes your life easier later. For example it could return separate lists of ingresses and egresses, which might be easier to work with (or maybe not!)

Either way, it's a bit broken at the moment, since it can return change points outside of the range covered by the phi array. The code in ```self.calcChangePoints``` could maybe look something like this:

```python
min_ecl = int(np.floor(phi.min()))
max_ecl = int(np.ceil(phi.max()))
eclipses = [e for e in range(min_ecl, max_ecl) if np.logical_and(e>phi.min(), e<phi.max())]
changepoints = []
for e in eclipses:
    changepoints.append(e-dist_cp)
    changepoints.append(e+dist_cp)
```

2019-04-30 15:02 UTC, StuartLittlefair commented on mcmcfit.py
> +        kernel = ampout * g.kernels.Matern32Kernel(tau, block=(-np.inf, changepoints[0]) )
Yeah - this is quite hard to get right. I think you've done it here, but we could manage it with fewer kernels, which might speed things up. It means changing the meaning of the parameters, so ```ampout``` becomes the *extra* amplitude visible when the WD is visible. Something like the figure below:

![Paper Ideas 2019 04 30](https://user-images.githubusercontent.com/4570807/56971082-770ec580-6b60-11e9-8505-988d2418d83f.png)

I think that could use simpler code and would use 5 kernels, whereas your code needs 7...

2019-05-01 09:09 UTC, wildjames commented on mcmcfit.py
>          changepoints = self.calcChangepoints(phi)
This version of `calcChangepoints` makes much more sense to me than the existing code, I'm in favour of it. 

I think you're right about changing the format that `calcChangepoints` returns; thinking about it it'd be cleaner if it gave back a list of

```python
min_ecl = int(np.floor(phi.min()))
max_ecl = int(np.ceil(phi.max()))
eclipses = [e for e in range(min_ecl, max_ecl) if np.logical_and(e>phi.min(), e<phi.max())]
changepoints = []
for e in eclipses:
    # When did the last eclipse end?
    egress = (e-1) - dist_cp
    # When does this eclipse start?
    ingress = e + dist_cp
    changepoints.append([egress, ingress])
```
Here, the egress is the egress of the _previous_ eclipse, so it comes first. Then, per your other comment below, the kernel just becomes
```python
# Global flicker
kernel = ampin * g.kernels.Matern32Kernel(tau)
# inter-eclipse flicker
for gap in changepoints:
    kernel += ampout * g.kernels.Matern32Kernel(tau, block=gap)
```
Much more streamlined!

2019-05-01 09:54 UTC, StuartLittlefair requested changes

2019-05-01 09:54 UTC, StuartLittlefair commented on mcmcfit.py
> +            egress = (e-1) - dist_cp
there's a sign error here. it should be

```
egress = (e-1) + dist_cp
ingress = e - dist_cp
```

2019-05-01 09:54 UTC, StuartLittlefair commented on mcmcfit.py
> +        eclipses = [e for e in range(min_ecl, max_ecl) if np.logical_and(e>phi.min(), e<phi.max())]
should be ```range(min_ecl, max_ecl+1)```

2019-05-01 09:54 UTC, StuartLittlefair commented on mcmcfit.py
> +            kernel += ampout * g.kernels.Matern32Kernel(tau, block=gap)
this is super neat

2019-05-01 09:54 UTC, StuartLittlefair commented on mcmcfit.py
> +        eclipses = [e for e in range(min_ecl, max_ecl) if np.logical_and(e>phi.min(), e<phi.max())]
and also ```np.logical_and(e > phi.min(), e < 1+phi.max())```

2019-05-02 07:49 UTC, wildjames commented
I accidentally pushed my watchparams changes to this PR! How do I remove them?

2019-05-02 07:52 UTC, StuartLittlefair requested changes
Oops. You’ve somehow added the watchparams script to this branch and thus pull request. We shouldn’t do that; good practice is to keep branches and PRs focussed on a single issue/change. 

Luckily in this instance it’s a single file so you can just “git rm” that file and commit the changes to this branch. It will leave a messy commit history but I’m ok with that

2019-05-02 08:01 UTC, wildjames commented
I've re-jigged how I have the code on my machine to try and head off this kind of thing, having each branch in a different folder so I don't have to `git checkout` every time I switch what I'm fiddling. Is this good practise?

2019-05-02 08:03 UTC, StuartLittlefair commented
Not really! If you go down that route you might as well not use git, but
just have a folder for each version...

Better to just get into the habit of checking which branch you are on... I
think there are terminal hacks you can use so this shows up in the prompt
if that helps...

Stuart Littlefair
Dept. of Physics & Astronomy
Univ. of Sheffield, Sheffield, S3 7RH

email: s.littlefair@shef.ac.uk
Phone: +44 114 2224525
Sent from my iPhone

On 2 May 2019, at 09:01, James Wild <notifications@github.com> wrote:

I've re-jigged how I have the code on my machine to try and head off this
kind of thing, having each branch in a different folder so I don't have to git
checkout every time I switch what I'm fiddling. Is this good practise?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/StuartLittlefair/lfit_python/pull/6#issuecomment-488583878>,
or mute the thread
<https://github.com/notifications/unsubscribe-auth/ABC35N7RBIZ73LNYIRTZCBDPTKNWTANCNFSM4HJLKG4A>
.

2019-05-02 08:56 UTC, StuartLittlefair approved these changes

2019-05-02 08:59 UTC, merged